volumes:
  prometheus_data: {}
  grafana_data: {}
  rabbitmq_data: {}
  rabbitmq_log: {}
services:

  techchallenge.rabbitmq:
    image: ${DOCKER_REGISTRY-}masstransit/rabbitmq
    container_name: techchallenge.rabbitmq
    environment: 
        RABBITMQ_DEFAULT_USER: 'guest'
        RABBITMQ_DEFAULT_PASS: 'guest'
    ports:
        - '15672:15672'
        - '5672:5672'
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
        - rabbitmq_log:/var/lib/rabbitmq

  techchallenge.api:
    image: solid12/techchallengeapi
    build:
      context: .
      dockerfile: TechChallenge.API/Dockerfile
    ports: 
       - "8080:8080"
       - "8081:8081"
  
  techchallenge.producer:
    image: solid12/techchallengeproducer
    build:
      context: .
      dockerfile: TechChallenge.Producer/Dockerfile
    ports: 
       - "5000:5000"
       - "5001:5001"

  techchallenge.tests:
    image: solid12/techchallengetests
    build:
      context: .
      dockerfile: .\TechChallenge.Producer.Tests\Dockerfile


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - 3031:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    container_name: grafana
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    volumes:
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards

  techchallengefiap.database:
      image: postgres:latest
      container_name: techchallengefiap.database
      environment: 
        - POSTGRES_DB=FIAP
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./.containers/techchallengefiap-db:/var/lib/postgresql/data1  
      ports:
        - 5432:5432

