version: '3.4'

volumes:
  grafana_data: {}

services:
  techchallengefiap.api:
    image: ${DOCKER_REGISTRY-}techchallengefiapapi
    container_name: techchallengefiap.api
    build:
      context: .
      dockerfile: TechChallengeFIAP.API/Dockerfile
    ports: 
       - "5000:5000"
       - "5001:5001"
  techchallengefiap.database:
      image: postgres:latest
      container_name: techchallengefiap.database
      environment: 
        - POSTGRES_DB=fiap
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./.containers/techchallengefiap-db:/var/lib/postgresql/data  
      ports:
        - 5432:5432
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    ports: 
      - 3000:3000
    volumes:
       - ./grafana:/etc/grafana/cofi
       - grafana_data:/var/lib/grafana
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
     - 3001:9090

