apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default # Certifique-se de que o namespace seja o correto
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'techchallenge-api'
        static_configs:
          - targets: ['techchallenge-api:8080'] # Nome do serviço Kubernetes e porta

      - job_name: 'techchallenge-producer'
        static_configs:
          - targets: ['techchallenge-producer:5000'] # Nome do serviço Kubernetes e porta
